apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2025-12-31T15:36:53Z"
  finalizers:
  - gke.networking.io/l4-netlb-v1
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "1767195449042655021"
  uid: fdb936ad-0b88-4123-b32e-07044fe07a28
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.234.96
  clusterIPs:
  - 34.118.234.96
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32035
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.47.155.254
      ipMode: VIP
